import { Gabarito } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'

const fontStyle = Gabarito({ subsets: ['latin'] })

export const metadata = {
  title: 'MyAnimeChris',
  description: 'Website Anime. Generated by Chrisandy Wiranata',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${fontStyle.className} bg-color-primary`}>
        <Navbar/>
        {children}
      </body>
    </html>
  )
}
